# ----------- CONFIGURABLE START -----------
title:            "blog - monostable.co.uk"
description:      "Code &amp; Electronics"
url:              https://blog.monostable.co.uk # Site url, without a slash at the end.
signoff:          "Kaspar Emanuel" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
include:
  - _redirects

links:
  - name:         posts
    url:          /
    external:     false
  - name:         rss
    url:          /feed.xml
    external:     false
  - name:         email
    url:          mailto:kaspar@monostable.co.uk
    external:     true
  - name:         github
    url:          https://github.com/monostable
    external:     true
  - name:         generative_art
    url:          https://generative.monostable.co.uk/
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
